const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/1-01.mp3",
    "image": "images/01.png",
    "transcript": "提問 這位先生怎麼了？\n(A) 他餓了\n(B) 他生病了\n(C) 他生氣了",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/1-02.mp3",
    "image": "images/02.png",
    "transcript": "提問 明美準備帶什麼去旅行？\n(A) 她準備了衣服和雨傘\n(B) 她準備了雨衣和手錶\n(C) 她準備了衣服和手錶",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/1-03.mp3",
    "image": "images/03.png",
    "transcript": "提問 草地上有什麼動物？\n(A) 有豬也有牛\n(B) 有很多羊和豬\n(C) 有幾隻牛和羊",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/1-04.mp3",
    "image": "images/04.png",
    "transcript": "提問 這兩位先生誰比較胖？\n(A) 這兩位先生一樣胖\n(B) 戴眼鏡的先生比較胖\n(C) 戴帽子的先生比較胖",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/1-05.mp3",
    "image": "images/05.png",
    "transcript": "提問 哥哥早上吃了什麼？\n(A) 哥哥吃了包子\n(B) 哥哥吃了麵包\n(C) 哥哥吃了漢堡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/1-06.mp3",
    "image": "images/06.png",
    "transcript": "提問 這兩天天氣怎麼樣？\n(A) 六月十七號比較熱\n(B) 六月十八號比十七號熱\n(C) 六月十八號沒有十七號那麼熱",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/1-07.mp3",
    "image": "images/07.png",
    "transcript": "提問 小東在哪裡吃飯？\n(A) 他在飯館吃飯\n(B) 他在客廳吃飯\n(C) 他在廚房吃飯",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/1-08.mp3",
    "image": "images/08.png",
    "transcript": "提問 小美今天穿什麼？\n(A) 她今天穿襯衫和褲子\n(B) 她今天穿大衣和裙子\n(C) 她今天穿襯衫和裙子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/1-09.mp3",
    "image": "images/09.png",
    "transcript": "提問 這位小姐的工作是什麼？\n(A) 她是護士\n(B) 她是病人\n(C) 她是醫生",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/1-10.mp3",
    "image": "images/10.png",
    "transcript": "提問 小貓兒睡在哪裡？\n(A) 小貓兒睡在窗上\n(B) 小貓兒睡在床上\n(C) 小貓兒睡在船上",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },

  // --- Part 2, IDs 11–25 (same structure, no image files in English question PDF, but we can still keep images since format uses them) ---
  {
    "id": 11,
    "part": 2,
    "question": "",
    "audio": "sounds/2-11.mp3",
    "image": "images/11.png",
    "transcript": "男：教室裡怎麼這麼安靜？\n女：因為正在考試。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 12,
    "part": 2,
    "question": "",
    "audio": "sounds/2-12.mp3",
    "image": "images/12.png",
    "transcript": "男：老師，這些東西要怎麼放？\n女：把同樣的東西放一起，水果和水果、飲料和飲料、蛋糕和蛋糕，別放錯了啊！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 13,
    "part": 2,
    "question": "",
    "audio": "sounds/2-13.mp3",
    "image": "images/13.png",
    "transcript": "男：你家離學校很近，為什麼要搬家？\n女：樓上的人常常把電視開得很大聲，我沒辦法睡覺。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 14,
    "part": 2,
    "question": "",
    "audio": "sounds/2-14.mp3",
    "image": "images/14.png",
    "transcript": "男：不上課的時候，你都做什麼？\n女：我喜歡畫畫。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 15,
    "part": 2,
    "question": "",
    "audio": "sounds/2-15.mp3",
    "image": "images/15.png",
    "transcript": "男：你下星期為什麼要請假？\n女：因為我要結婚了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 16,
    "part": 2,
    "question": "",
    "audio": "sounds/2-16.mp3",
    "image": "images/16.png",
    "transcript": "男：這東西要100元！明美，我想買這個，可是還少30元，怎麼辦？\n女：我先用信用卡幫你付錢吧！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 17,
    "part": 2,
    "question": "",
    "audio": "sounds/2-17.mp3",
    "image": "images/17.png",
    "transcript": "男：這隻小黑狗是你的嗎？我記得你還有一隻貓，對吧？\n女：我是有一隻狗和一隻貓，但是都不是黑色的。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 18,
    "part": 2,
    "question": "",
    "audio": "sounds/2-18.mp3",
    "image": "images/18.png",
    "transcript": "女：你幫我看看這張紙上說了什麼？\n男：喔，這是學費通知嘛！上面說今年可以上網用信用卡付學費。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 19,
    "part": 2,
    "question": "",
    "audio": "sounds/2-19.mp3",
    "image": "images/19.png",
    "transcript": "男：你不舒服嗎？\n女：我只是有一點兒累。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 20,
    "part": 2,
    "question": "",
    "audio": "sounds/2-20.mp3",
    "image": "images/20.png",
    "transcript": "男：您好，請問這家百貨公司在哪裡？\n女：你會先經過火車站，然後從車站往前走兩個路口就到了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 21,
    "part": 2,
    "question": "",
    "audio": "sounds/2-21.mp3",
    "image": "images/21.png",
    "transcript": "男：高太太有幾個孩子？\n女：高太太有兩個兒子。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 22,
    "part": 2,
    "question": "",
    "audio": "sounds/2-22.mp3",
    "image": "images/22.png",
    "transcript": "男：請問這些電腦要放在教室嗎？\n女：教室裡沒地方放了，先放在辦公室吧！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 23,
    "part": 2,
    "question": "",
    "audio": "sounds/2-23.mp3",
    "image": "images/23.png",
    "transcript": "男：妳覺得什麼時候去台灣玩最好?\n女：我覺得台灣的春天還不錯，可以很舒服地旅行。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 24,
    "part": 2,
    "question": "",
    "audio": "sounds/2-24.mp3",
    "image": "images/24.png",
    "transcript": "女1：妳們打掃哪裡了？\n女2：我們打掃客廳了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 25,
    "part": 2,
    "question": "",
    "audio": "sounds/2-25.mp3",
    "image": "images/25.png",
    "transcript": "女：你想把洗衣機放在哪兒？放在樓梯旁邊怎麼樣？\n男：放在那裡太吵了，放在浴室裡吧。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 26,
    "part": 3,
    "question": "",
    "audio": "sounds/3-26.mp3",
    "image": "images/26.png",
    "transcript": "男：你好，我要買這兩本書。\n女：現在買三本書就送一本，先生您要再買一本嗎？\n男：不用了！我想用信用卡付錢。\n女：沒問題，但是付錢的地方在一樓。\n男：請問這位小姐要客人去哪兒？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 27,
    "part": 3,
    "question": "",
    "audio": "sounds/3-27.mp3",
    "image": "images/27.png",
    "transcript": "男：請問火車站怎麼走？\n女：你往前走三分鐘會看見一間醫院。\n男：醫院嗎？\n女：對，火車站就在醫院旁邊。\n男：請問火車站在哪裡？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 28,
    "part": 3,
    "question": "",
    "audio": "sounds/3-28.mp3",
    "image": "images/28.png",
    "transcript": "男：請問這本書我可以借多久？\n女：今天是9月1日，如果你是老師可以借三個星期。\n男：我不是老師，我是學生。\n女：學生可以借兩個星期。\n男：請問學生可以借書借多久？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 29,
    "part": 3,
    "question": "",
    "audio": "sounds/3-29.mp3",
    "image": "images/29.png",
    "transcript": "男：這個星期日一起去看電影吧！\n女：好啊，早上八點怎麼樣？電影票比較便宜。\n男：太早了啦！上午十一點好不好？\n女：好啊！不過你要請客喔！\n男：請問，他們星期日要做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 30,
    "part": 3,
    "question": "",
    "audio": "sounds/3-30.mp3",
    "image": "images/30.png",
    "transcript": "男：唉唷！我的頭好痛。\n女：你怎麼常常不舒服啊！\n男：沒辦法，昨天腳痛，今天頭痛。\n女：我還是陪你去看醫生吧！\n男：請問這位先生今天怎麼了？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 31,
    "part": 3,
    "question": "",
    "audio": "sounds/3-31.mp3",
    "image": "images/31.png",
    "transcript": "男：放假的時候我們去日本玩好不好？\n女：現在去日本很貴，我不要。\n男：你不會又想在家裡睡覺了吧？\n女：我要去公司，把沒做完的工作做完。\n男：請問這位小姐放假的時候想做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 32,
    "part": 3,
    "question": "",
    "audio": "sounds/3-32.mp3",
    "image": "images/32.png",
    "transcript": "男：小美，今天晚上一起去烤肉，好不好？\n女：烤肉？可是明天就要考試了，我想去圖書館唸書。\n男：大明今天生日，他希望我們能幫他慶祝生日。\n女：嗯～我想你去就好了，我還是比較想去圖書館。\n男：請問小美晚上要做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 33,
    "part": 3,
    "question": "",
    "audio": "sounds/3-33.mp3",
    "image": "images/33.png",
    "transcript": "男：小月，你通知記者了嗎？\n女：什麼記者？\n男：今天下午開會的事，妳忘了嗎？\n女：對不起，經理，我現在就打電話通知他們。\n男：這位小姐現在要做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 34,
    "part": 3,
    "question": "",
    "audio": "sounds/3-34.mp3",
    "image": "images/34.png",
    "transcript": "男：你好，請給我一間房間。\n女：我看看，四樓的房間可以嗎？\n男：我不喜歡四樓，可以換嗎？\n女：那五樓的六號房吧！\n男：請問這位先生住幾樓？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 35,
    "part": 3,
    "question": "",
    "audio": "sounds/3-35.mp3",
    "image": "images/35.png",
    "transcript": "男：你什麼時候要來我家拿書？\n女：明天可以嗎？書重不重？\n男：明天可以，但是你一個人拿太重了，請人來幫妳吧！\n女：好，我請我的朋友和我一起去。\n男：請問女生明天要去男生家做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 36,
    "part": 3,
    "question": "",
    "audio": "sounds/3-36.mp3",
    "image": "images/36.png",
    "transcript": "男：請問，這間房間一個月多少錢？\n女：一個月五千元，有電視和冰箱。\n男：有冷氣嗎？\n女：這間沒有，七千塊的才有。\n男：請問這個房間裡面有什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 37,
    "part": 3,
    "question": "",
    "audio": "sounds/3-37.mp3",
    "image": "images/37.png",
    "transcript": "男：這雙鞋子多少錢？\n女：這一雙8000元。\n男：好貴，你們的鞋子不好看又不好穿。\n女：先生，你可以多去別家看看。\n男：請問他們在做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 38,
    "part": 3,
    "question": "",
    "audio": "sounds/3-38.mp3",
    "image": "images/38.png",
    "transcript": "男：小姐，請問一位嗎？\n女：我們一共四位，只是我先到。\n男：那請您這邊坐，這是菜單。請問您要先點菜嗎？\n女：我想等人都來了，再一起點，麻煩先給我一杯開水。\n男：請問這位小姐想要先做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 39,
    "part": 3,
    "question": "",
    "audio": "sounds/3-39.mp3",
    "image": "images/39.png",
    "transcript": "男：已經晚上十點了！你先去刷牙，然後上床睡覺！\n女：可是我還想看電視節目。我可以一邊刷牙一邊看嗎？\n男：不行！再不睡覺，你明天上課一定遲到。\n女：好吧！那我先去刷牙。\n男：請問這個女孩等一會兒要先做什麼？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 40,
    "part": 3,
    "question": "",
    "audio": "sounds/3-40.mp3",
    "image": "images/40.png",
    "transcript": "男：前面那個人是我們的校長。\n女：哪位？講電話的那位嗎？\n男：不，他站在看報紙的先生旁邊。\n女：喔，我看到了，他手上拿著大衣。\n男：請問哪一位是校長？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },

  // --- Part 4 (41–50, with descriptive options) ---
  {
    "id": 41,
    "part": 4,
    "question": "",
    "audio": "sounds/4-41.mp3",
    "transcript": "男：請問一下，這兒晚上有什麼好玩的地方可以去？\n女：附近有一個市場，晚上有很多好吃、好玩的，很熱鬧。\n男：有什麼有名的地方嗎？\n女：您可以坐車去參觀世界最高的大樓，上大樓去看風景，晚上的風景很漂亮的。\n男：這位先生想知道什麼？",
    "options": ["（A）晚上可以去哪兒玩", "（B）有名的大樓在哪裡", "（C）這位小姐要去哪兒玩", "（D）這附近有什麼好吃的東西"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 42,
    "part": 4,
    "question": "",
    "audio": "sounds/4-42.mp3",
    "transcript": "男：太太，我想請小麗一家人到中華樓吃飯。\n女：那兒的中國菜是不錯，不過小麗的孩子從小在美國長大，可能不習慣用筷子吧！\n男：他們用筷子吃飯的機會不是天天有的。這些孩子長大以後，會感謝我的。\n女：好吧，那就去中華樓吧！\n男：這兩個人為什麼決定去中華樓吃飯？",
    "options": ["（A）因為那裡的服務很不錯", "（B）因為那裡的菜天天不同", "（C）因為小朋友想吃中國菜", "（D）因為想讓客人吃中國菜"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 43,
    "part": 4,
    "question": "",
    "audio": "sounds/4-43.mp3",
    "transcript": "男：您好，我要掛號。\n女：掛號請到門口的右邊排隊。\n男：哇，掛號的人真多。\n女：現在掛號的方法很多，您如果不喜歡排隊，下一次可以先在家裡，使用電腦網路掛號，再來醫院看病。\n男：這位小姐最後的意思是什麼？",
    "options": ["（A）要這位先生先排隊", "（B）要這位先生快去看病", "（C）告訴這位先生其他掛號方式", "（D）告訴這位先生怎麼上網掛號"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 44,
    "part": 4,
    "question": "",
    "audio": "sounds/4-44.mp3",
    "transcript": "男：陳小姐，來買東西啊？\n女：是啊，林太太剛搬家，我想買幾個碗盤送她。\n男：原來林太太搬走了，她搬到哪兒去了？\n女：離這兒不遠的郊區。\n男：這位小姐說了什麼？",
    "options": ["（A）她要搬到附近的郊區", "（B）她來幫林太太買東西", "（C）她要送禮物給林太太", "（D）林太太請她送東西到郊區"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 45,
    "part": 4,
    "question": "",
    "audio": "sounds/4-45.mp3",
    "transcript": "男：小美，這個白色的手機不錯，妳覺得呢？\n女：我想買和哥哥一樣的手機。\n男：為什麼呢？我覺得黑色的手機沒有白色的好看。\n女：因為那個黑色的手機比較便宜，不過最重要的是手機裡的音樂都很特別，我很喜歡。\n男：小美選擇黑色手機主要的原因是什麼？",
    "options": ["（A）因為這支手機不貴", "（B）因為她想和哥哥一樣", "（C）因為她喜歡手機裡的音樂", "（D）因為她哥哥要送她黑色手機"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/4-46.mp3",
    "transcript": "男：何小姐，這三天謝謝妳的幫忙。\n女：不用那麼客氣，這是我應該做的。\n男：希望有機會能再來這裡。對了，如果妳來美國玩，記得來找我。換我帶妳到處走走。\n女：好啊，謝謝你。祝你一路平安，再見。\n男：從這兩個人講的話可以知道這位先生怎麼樣？",
    "options": ["（A）要回美國去了", "（B）三天前來美國玩兒", "（C）想請何小姐跟他一起回去", "（D）這三天帶著何小姐到處走走"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/4-47.mp3",
    "transcript": "男：下星期妳是不是要去日本？\n女：是啊，請問有什麼事嗎？\n男：我想請妳幫我帶一個東西給我朋友。\n女：不好意思，我要帶的東西很多，可能不太方便。\n男：這位小姐的意思是什麼？",
    "options": ["（A）她不想送東西給朋友", "（B）她不想答應對方的要求", "（C）她不想讓朋友覺得麻煩", "（D）她想知道要幫對方帶多少東西"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/4-48.mp3",
    "transcript": "男：你好，我們是不是上過一樣的課？\n女：嗯！你是張強吧！我在李老師的課上看過你，你覺得她的課怎麼樣？\n男：她的課很無聊，害我不及格，還得重修。對了，妳怎麼知道我的名字？難道妳也是四年級的學生？\n女：同學，我在課堂上總共見過你四次，你都在睡覺，歡迎你繼續修我的課。\n男：關於這段對話，下面哪一個是對的？",
    "options": ["（A）這位小姐曾經教過張強", "（B）這位小姐很高興看見張強", "（C）張強對這位小姐印象深刻", "（D）張強希望能和這位小姐一起上課"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/4-49.mp3",
    "transcript": "男：星期六我打算去爬山，要不要一起去？\n女：好啊！幾點出發？\n男：我們大概下午一點出發，爬三個多小時就回來。\n女：但是現在這個季節，山上的天氣變化很大，這麼晚去可能有點危險。\n男：這位小姐的意思是什麼？",
    "options": ["（A）早點出門比較安全", "（B）晚上去爬山很危險", "（C）等到星期六再決定", "（D）這種季節最好別爬山"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/4-50.mp3",
    "transcript": "男：小英，剛剛那位小姐是妳的同學嗎？\n女：不是，她是我的老師。\n男：什麼？她那麼年輕，怎麼可能是妳的老師。\n女：她比我大十歲，明年就四十歲了。\n男：小英的意思是什麼？",
    "options": ["（A）她的生日快到了", "（B）她快要四十歲了", "（C）老師的年紀比她大", "（D）老師已經四十歲了"],
    "answer": "C",
    "remark": ""
  }
];
